[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
evm_version = 'shanghai'
viaIR = true


remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
]

[dependencies]
openzeppelin-contracts = { git = "https://github.com/OpenZeppelin/openzeppelin-contracts.git", tag = "v5.0.0" }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
